# torchtitan Config.toml
# NOTE: this toml config is a preset for 64 A100 GPUs.

[job]
dump_folder = "./outputs"
description = "250m Unshared Run"

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace_shared_layer"
profile_freq = 100

[metrics]
log_freq = 10
enable_tensorboard = true
save_tb_folder = "tb"

[model]
name = "llama3"
flavor = "250M_unshared"
hf_assets_path = "./assets/hf/Llama-3.1-8B"
# converters = ["float8"]
[model.shared_attn]
enabled = false
attn_sharing = true
head_sharing = true
grouping = 1
rank = 128
two_step = false

[model.layer_sharing]
enabled = false
rank = 256
sharing = [[0,],[1, 2, 3,], [4, 5, 6,], [7, 8, 9,], [10, 11, 12,], [13, 14, 15,], [16, 17, 18,], [19, 20, 21,], [22, 23, 24,], [25,]]


[optimizer]
name = "AdamW"
lr = 3e-4
eps = 1e-8

[lr_scheduler]
warmup_steps = 2000  # lr scheduler warm up
decay_ratio = 0.8  # lr scheduler decay ratio, 80% of the train steps
decay_type = "cosine"
min_lr_factor = 0.1

[training]
local_batch_size = 10
seq_len = 2048
max_norm = 1.0  # grad norm clipping
steps = 77000
compile = true
dataset = "fw_edu"

[parallelism]
data_parallel_replicate_degree = 8
data_parallel_shard_degree = 1
tensor_parallel_degree = 1
pipeline_parallel_degree = 1
context_parallel_degree = 1

[checkpoint]
enable_checkpoint = true
folder = "250m_combined_checkpoints"
interval = 500
last_save_model_only = true
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = "none"  # ["none", "selective", "full"]
selective_ac_option = "op"  # "int" = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_fsdp_float8_all_gather = false
precompute_float8_dynamic_scale_for_fsdp = false
filter_fqns = ["output"]

[validation]
enabled = false
dataset = "fw_edu_val"
freq = 100
steps = -1
